version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: marketplaceturismo:1.0
    container_name: marketplaceturismo-app
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - db
    volumes:
      - ./apache/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./:/var/www
    environment:
      DB_HOST: db
      DB_DATABASE: marketplaceturismo
      DB_USERNAME: root
      DB_PASSWORD: secret

  db:
    image: mysql:5.7
    container_name: marketplaceturismo-db
    restart: unless-stopped
    ports:
        - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: marketplaceturismo

volumes:
  db-data:
